# Generated by Django 4.1.5 on 2023-01-22 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_baseuser_options'),
        ('courses', '0002_alter_course_lecturers_courseregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_results', to='users.student')),
            ],
            options={
                'verbose_name': 'Course Result',
                'verbose_name_plural': 'Courses Results',
            },
        ),
    ]
