# Generated by Django 4.1.5 on 2023-01-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresult',
            name='ca_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='courseresult',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
