# Generated by Django 4.1.5 on 2023-01-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_result_courseresult_resultsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresult',
            name='ca_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='courseresult',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
