# Generated by Django 4.1.5 on 2023-01-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courseresult_ca_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
