# Generated by Django 4.1.5 on 2023-02-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_baseuser_options'),
        ('courses', '0007_alter_courseregistration_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturers',
            field=models.ManyToManyField(to='users.lecturer'),
        ),
    ]
