# Generated by Django 4.1.5 on 2023-02-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_baseuser_options'),
        ('courses', '0010_alter_course_lecturers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturers',
            field=models.ManyToManyField(to='users.lecturer'),
        ),
    ]
