# Generated by Django 4.1.5 on 2023-02-05 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0002_announcement_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='read_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='sent_to',
            field=models.ManyToManyField(blank=True, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
